# Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "test2",
    "email": "test2@example.com",
    "password": "test2"
}

### Login
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "ashokbuxar41@gmail.com",
    "password": "buxarbuxar"
}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1ZjRjZDc3NTAwNzAzZWFjMDA5YzNhYzIiLCJleHAiOjE2MDE0MjEwMzUzNjJ9.k4NkKXTk0JU7iFQs0-IaLgt-2hwwBKIecFRK9_Zas_g


####################
### Surveys
####################

### get all surveys for user

GET http://localhost:8000/users
Authorization: Bearer {{token}}

### get single Survey

GET http://localhost:8000/api/survey/5f550e9600f4617400dbb38b
Authorization: Bearer {{token}}

### create Survey

POST http://localhost:8000/api/survey
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "survey 1",
    "description": "lorem10"
}

### update Survey

PUT http://localhost:8000/api/survey/5f550e9600f4617400dbb38b
Authorization: Bearer {{token}}
Content-Type: application/json

{   "userId": "6",
    "name": "survey 6",
    "description": "lorem 100"
}

### delete Survey

DELETE http://localhost:8000/api/survey/5f559f2600b0231700bf97e9
Authorization: Bearer {{token}}
